Added auth using passport
hackkerala/hhkweb pull request #2
Opened 2020-03-18 16:54 UTC by kaiiyer

Features Added:
- Server with Node.js and Express
- Setting up Passport
- Encrypted user passwords using bcrypt
- Restricting access to routes for logged in users(Once logged in you don't have to revisit the login page before you actually logout)
- Flash messages
- <b>No DB integrated !!</b>

2020-03-20 12:45 UTC, jagannathBhat requested changes
Can the following changes be made?

1. Delete all .ejs files. We can use the pages I designed instead.
2. Comment the routes leading to the .ejs file in server.js. I will add the routes myself.
3. Make all auth routes starting with '/api'. Like the post request '/register' should be '/api/register'.
4. Do we really need the requirements.txt file. We can install from package.json right?
5. Move all files from hhk-auth to the root folder.

2020-03-20 14:15 UTC, jagannathBhat approved these changes

2020-03-20 14:31 UTC, athul commented on server.js
>  	res.render('register.ejs')
Still `.ejs` ?

2020-03-20 14:33 UTC, kaiiyer commented on server.js
>  	res.render('register.ejs')
File deleted aa. Newfile add cheiyumbo rename cheital mati

2020-03-20 14:35 UTC, athul approved these changes
LGTM

2020-03-21 03:31 UTC, athul commented
@jagannathbhat Merge when you're ready

2020-03-21 03:32 UTC, merged

2020-03-21 03:32 UTC, jagannathBhat commented
done